### PR TITLE
Update Password Recovery

### PR DESCRIPTION
**Pull request by thi67**
- Add Firefox Browser
For infos the client need to be set on same target system as Firefox (Exemple Firefox(x64) need Client(x64) that because I'have set the target on "Any CPU")

### CODE REVIEW

**Comment by NYAN-x-CAT** [comment]
Thank you @thi67  for your continued support. I will make a DLL as a simple plugin to decrease the stub's size.

**Comment by NYAN-x-CAT** [comment]
It seems that this class won't work with new versions of FX. have you tried using this class?

**Comment by thi67** [comment]
I'v try and work perfect but you need same target client as firefox target platform because it use 3 dll from the installation.

**Comment by thi67** [comment]
Test

**Comment by thi67** [comment]
Great work dude continues like this,
I would like to thank you again for your project, I have never seen a rat so stable and so light in C#.

For me it only needs a few more features and I would like to help sometimes with the project. 
I don't have a lot of time because of my work but let's say that programming for me is a hobby.

PS: Sorry for my poor English I am French and I speak German too but I don't use English every day to compose sentences.

**Comment by NYAN-x-CAT** [comment]
Thank you @thi67 for your reply, You are welcome anytime to edit and pull request! This is also a hobby project for me. I will merge it soon after adding some features.

**Pull request closed without merging**
